INSERT INTO Users (Username,Password,Bill) VALUES ('admin','Admin',20000);
INSERT INTO Users (Username,Password,Bill) VALUES ('test','tester',5000);
INSERT INTO Users (Username,Password,Bill) VALUES ('user','qerty',0);

INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Apex Legends',300,799);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (1,'Biomutant',1169,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'CoDMW',1099,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Control',850,1300);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Cyberpunk 2077',1300,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Darksiders Genesis',550,1000);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Death Stranding',2399,3499);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (1,'Devil May Cry 5',1100,1599);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Diablo IV',1550,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'DOOM Eternal',1500,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Half-life alyx',750,1085);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Halo infinite',1300,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Journey to the savage planet',340,650);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Metro Exodus',1099,1600);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Minecraft Dungeons',550,870);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Sekiro Shadow die twice',1299,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'TABS',150,360);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'The Sinking City',1660,1999);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'WoW Shadowlands',1300,1750);
