INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Apex Legends',799,300);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (1,'Biomutant',1999,1169);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'CoDMW',1999,1099);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Control',1300,850);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Cyberpunk 2077',1999,1300);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Darksiders Genesis',1000,550);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Death Stranding',3499,2399);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (1,'Devil May Cry 5',1599,1100);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Diablo IV',1999,1550);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'DOOM Eternal',1999,1500);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Half-life alyx',1085,750);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Halo infinite',1999,1300);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Journey to the savage planet',650,340);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Metro Exodus',1600,1099);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (0,'Minecraft Dungeons',870,550);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'Sekiro Shadow die twice',1999,1299);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'TABS',360,150);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'The Sinking City',1999,1660);
INSERT INTO Games (typeOfGame,GameName,BasePrice,OurPrice) VALUES (2,'WoW Shadowlands',1750,1300);
